
data:
  metadata: data/sabdab_2603/processed/sabdab_2603/metadata.json
  pdb_dir: data/sabdab_2603/processed/pdb
  samples_dir: data/sabdab_2603/processed/sabdab_2603/samples
  train_ids: data/sabdab_2603/processed/split_onetest/train_prot_ids.txt
  val_ids: data/sabdab_2603/processed/split_onetest/val_prot_ids.txt
  test_ids: data/sabdab_2603/processed/split_onetest/test_prot_ids.txt
  train_clusters: data/sabdab_2603/processed/split_onetest/train_prot_cluster.txt
  batch_size: 1
  num_workers: 1
  n_steps: 200
  forward_chunk_size: 128
  max_antigen_len: 256  # 384


model:
  ppi_ckpt: "/root/private_data/luog/codex/IgGM/checkpoints/esm_ppi_650m_ab.pth"
  design_ckpt: "/root/private_data/luog/codex/IgGM2/outputs/lightning-stage_one-T5/checkpoints/last.ckpt" # "/root/private_data/luog/codex/IgGM2/outputs/lightning-stage_one-T4/checkpoints/best-epoch=949-val_tm_score=0.0000.ckpt" 
  igso3_buffer: "/root/private_data/luog/codex/IgGM/checkpoints/igso3_buffer.pth"

optimizer:
  lr: 5.0e-6 # 1.0e-6
  weight_decay: 1.0e-2
  grad_clip: 10.0

scheduler:
  name: cosine
  t_max: 10
  eta_min: 1.0e-6

loss:
  vio_weight: 0.02

metrics:
  dockq_threshold: 0.23

trainer:
  max_epochs: 200
  precision: bf16 # bf16-mixed
  accelerator: gpu
  devices: [0] 
  log_every_n_steps: 5
  accumulate_grad_batches: 1
  num_sanity_val_steps: 0
  strategy: ddp
  ddp_static_graph: false
  ddp_find_unused_parameters: true

wandb:
  disabled: true # true or false
  project: IgGM
  run_name: iggm-stage_one-T4-222
  entity: "mllm-csu"
  api_key: "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"

runtime:
  output_dir: outputs/lightning-stage_one-T4-222
  seed: 56
  resume: False
  run_test: true

stage_training:
  stage1_epochs: 0
  stage2_enable_seq_recovery: true
  mix_cdr_h3: 4
  mix_cdr_h1: 2
  mix_cdr_h2: 2
  mix_cdr_all: 2
  lazy_cache_size: 128
  occupancy_mode: joint_predict
  